export const STAFF = 'staff'
export const DRIVER = 'driver'
export const CAPTAIN = 'captain'
export const ACCOUNTANT = 'accountant'
export const MANAGER = 'manager'
export const ADMIN = 'admin'
export const MALE = 'male'
export const FEMALE = 'female'
